### PR TITLE
Spec homepage - Elements updated as per the changes in Experience Cloud

### PR DESCRIPTION
**Pull request by PavanKumarN8**
Hi @sigadamvenkata, Elements updated as per the changed options under Experience Cloud.

### CODE REVIEW

**Comment by PavanKumarN8** [comment]
Local Test Run Results
image

**Review by JackySun9 — CHANGES_REQUESTED** [review]
fix eslint errors

**Review by sigadamvenkata — APPROVED** [review]

**Comment by JackySun9** [comment]
please fix eslint error, still see a lot

**Review by skumar09 — CHANGES_REQUESTED** [review]
@PavanKumarN8 : 
It's really good to see that your PRs are meeting most of the NALA style and format requirements, except for ESLint. Could you please also start taking care of ESLint failures?

cc : @JackySun9 @sigadamvenkata @Dli3 @amauch-adobe

**Review by JackySun9 — APPROVED** [review]

**Review by skumar09 — APPROVED** [review]

**Pull request merged**
