### PR TITLE
MWPW-130801 : Update run.sh for label nala-run

### PR DESCRIPTION
**Pull request by skumar09**
[MWPW-130801](https://jira.corp.adobe.com/browse/MWPW-130801) : Update nala test runs for label `'run-nala'` 

PR fixes the below issue:

**Issue 1:**  If the PR has the label` run-nala`,  it runs only Milo automation scripts. 
**Expected:** If the PR has the Label `run-nala`, then it should run` all project(s)` automation scripts from the Nala repo
It should run all `.config.js` file tests i.e. all projects automation scripts: like `bacom, dc, feds, uar, milo` etc

Note 1: This PR is a continuation of MWPW-130636 ( PR: https://github.com/adobecom/nala/pull/113 )

**Info:** Along with this PR, the following feature is added
**Feature:** If PR does not have any label, then by `default it will run only Milo automation scripts`

### CODE REVIEW

**Review by amauch-adobe — APPROVED** [review]
Approved.

**Comment by amauch-adobe** [comment]
@skumar09 is there a reason this one is from a fork, just curious since you usually just do a branch.

**Review by chadsunvice — APPROVED** [review]
lgtm! 👍

**Comment by skumar09** [comment]
> I like the idea of running all the NALA checks when the specific tag is given, but I think we should fix all the tests failing. I took a look at the run and looks like most of the checks are failing since the `IMS_PASS` & `IMS_EMAIL` values are not present. For FEDS side, that is 100% the motive the `userprofile.test.js` checks are failing.
> 
> How should we fix this issue moving forward @amauch-adobe @skumar09 ?

**Comment by skumar09** [comment]
> > I like the idea of running all the NALA checks when the specific tag is given, but I think we should fix all the tests failing. I took a look at the run and looks like most of the checks are failing since the `IMS_PASS` & `IMS_EMAIL` values are not present. For FEDS side, that is 100% the motive the `userprofile.test.js` checks are failing.
> > How should we fix this issue moving forward @amauch-adobe @skumar09 ?

**Comment by skumar09** [comment]
> I like the idea of running all the NALA checks when the specific tag is given, but I think we should fix all the tests failing. I took a look at the run and looks like most of the checks are failing since the `IMS_PASS` & `IMS_EMAIL` values are not present. For FEDS side, that is 100% the motive the `userprofile.test.js` checks are failing.
> 
> How should we fix this issue moving forward @amauch-adobe @skumar09 ?

- Yeah, quite a few test failures related to authentication,  do we need different authentication ids for feds?
- Also, I am observing  `run-nala` execution is taking more than 2hrs. ( Currently, it is executing more than 900+ test scripts ( all projects / all platforms) and failing tests are contributing to increasing the execution time ). Fixing the test failures will reduce this.
   - Currently working on fixing other failures,

**Comment by amauch-adobe** [comment]
@skumar09 and @chadsunvice, the IMS_PASS and IMS_EMAIL are available for the Nala Repository only.  GitHub documentation states it will not be available to be passed to PRs that include Forks for security reasons (see [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories)).

The way to get around this is to make local branches rather than forks.  Where we are a public repository and not a private repository by default GitHub doesn't allow secrets to be passed to forks.

**Comment by skumar09** [comment]
This PR is not required anymore...

**Pull request closed without merging**
