### PR TITLE
Remove skip from commerce tests

### PR DESCRIPTION
**Pull request by afmicka**
Update commerce tests not to be skip entirely, only with @nopr tag. 
Added few more commerce smoke tests

### CODE REVIEW

**Comment by afmicka** [comment]
@skumar09 @Dli3 guys, i am not sure how to resolve these complaints from eslint. Running
`npx eslint --fix`
creates those too long lines and not finding WebUtil. 

Tests are executing, don't see any impact, but if you have any idea, please let me know.

**Comment by skumar09** [comment]
> files creates those too long lines and not finding WebUtil.

- ESlint issues related to `WebUtil` can be ignored for now. 
- Other ESlint issue i am fixing bit manually as` npx eslint --fix ` won't fix all

**Review by skumar09 — APPROVED** [review]

**Review by JackySun9 — APPROVED** [review]

**Comment by afmicka** [comment]
@Dli3 @skumar09 @JackySun9 
marketo tests are failing here. Not related to the PR and would like to merge this one, but please take a look into failing tests.

**Comment by Dli3** [comment]
> @Dli3 @skumar09 @JackySun9 marketo tests are failing here. Not related to the PR and would like to merge this one, but please take a look into failing tests.

I'll look into it. Thanks @afmicka .

**Pull request merged**
