### PR TITLE
MWPW-130540 - add commerce feature tests

### PR DESCRIPTION
**Pull request by afmicka**
Adding tests for OST UI and commerce features. 
https://jira.corp.adobe.com/browse/MWPW-130540

### CODE REVIEW

**Review by chadsunvice — APPROVED** [review]

**Comment by afmicka** [comment]
@chadsunvice @skumar09 Our tests need logging-in. They are not picking up IMS_PASS and IMS_EMAIL with run-nala on the branch. Could you please guide how to ensure that account details are retrieved when running tests on PRs from the branch?

**Comment by skumar09** [comment]
> @chadsunvice @skumar09 Our tests need logging-in. They are not picking up IMS_PASS and IMS_EMAIL with run-nala on the branch. Could you please guide how to ensure that account details are retrieved when running tests on PRs from the branch?

@afmicka : 
- PR run action job won't pick up the GitHub environment variables due to restrictions from GitHub,
**Info from GitHub:** 
image

-  We are working on any alternatives on this. We can bypass the sign-in tests on PR run, but the same can be run daily run jobs.

**Comment by amauch-adobe** [comment]
> > @chadsunvice @skumar09 Our tests need logging-in. They are not picking up IMS_PASS and IMS_EMAIL with run-nala on the branch. Could you please guide how to ensure that account details are retrieved when running tests on PRs from the branch?
> 
> @afmicka :
> 
> * PR run action job won't pick up the GitHub environment variables due to restrictions from GitHub,
>   **Info from GitHub:**
>   image
> * Also, on PR branches, IMS is not enabled i belive, ( I think IMS is whitelisted only on Main and Stage branches )
> * We are working on any alternatives on this. We can bypass the sign-in tests on PR run, but the same can be run daily run jobs.

@afmicka, the restriction is GitHub doesn't allow forked branches to have access to repository secrets in GitHub Actions on PRs, it is a security measure put in place.  That being said I have the account credentials for these secrets if you would like to add it to your fork so you can at least see that it runs just fine on your fork prior to making a PR to the parent.  Just ping me.

**Comment by afmicka** [comment]
@skumar09 @amauch-adobe Thanks both. The thing is that these tests need to be run with every PR raised from commerce team to ensure that the changes do not affect Offer Selector Tool and any change coming from commerce team can affect it greatly. Those PRs are usually raised from different forks (each dev has its own). To access /tools/ost from each branch it needs access token to be appended to the tool url. Tokens are temporary. To retrieve the token we have a step in beforeAll to login to adobe.com page (or any live production page) and retrieve it and then append the value to the url when each tests is executed. 
For example, it looks like: https://mwpw-139764--milo--axelcureno.hlx.page/tools/ost?token=< retrieved token value >

That being said, it looks to me that i would need to pass the credentials in beforeAll hook (use or write the login steps there with exposed credentials) but then i need the testing account that is not going to be asked to verify it with the code sent to the email, or randomly asked to add secondary email, security questions etc. I can try with the testing accounts we were using in other testing automation repos or use the credentials from you if you have any dedicated testing account.

**Comment by skumar09** [comment]
> To retrieve the token we have a step in beforeAll to login to adobe.com page (or any live production page) and retrieve it and then append the value to the url when each tests is executed. For example, it looks like: https://mwpw-139764--milo--axelcureno.hlx.page/tools/ost?token=< retrieved token value >
> 
> That being said, it looks to me that i would need to pass the credentials in beforeAll hook (use or write the login steps th

@afmicka : are there any other ways to get a token? like using the `curl` command or any `other API` requests? 
can we have a call sometime when you are available to discuss this?

**Comment by afmicka** [comment]
> > To retrieve the token we have a step in beforeAll to login to adobe.com page (or any live production page) and retrieve it and then append the value to the url when each tests is executed. For example, it looks like: https://mwpw-139764--milo--axelcureno.hlx.page/tools/ost?token=< retrieved token value >
> > That being said, it looks to me that i would need to pass the credentials in beforeAll hook (use or write the login steps th
> 
> @afmicka : are there any other ways to get a token? like using the `curl` command or any `other API` requests? can we have a call sometime when you are available to discuss this?
> 
> cc : @amauch-adobe

No, seems that there is not. Let discuss it in a call on Monday (your morning, my evening) and will bring some developers in to tackle the topic together.

**Comment by afmicka** [comment]
@skumar09 @chadsunvice I have removed the OST tests (the ones needing login) for the time being until we discuss with devs whether we have a solution for PR checks or leave them only for daily run. The rest of the tests are basic checks that are ready to be merged. Removed the "do not merge " label. 

Please review and merge if ok.

**Comment by skumar09** [comment]
> @skumar09 @chadsunvice I have removed the OST tests (the ones needing login) for the time being until we discuss with devs whether we have a solution for PR checks or leave them only for daily run. The rest of the tests are basic checks that are ready to be merged. Removed the "do not merge " label.
> 
> Please review and merge if ok.

@afmicka :  sure, thanks for the update; PR looks good; I will merge it.  Can you please make the following changes as part of another PR?

I have recently updated all the Milo tests to be run using the Milolibs param ([PR-240](https://github.com/adobecom/nala/pull/240)), so can you please do the following updates as part of the next PR? ( Please refer to any of the Milo tests.)
   `const miloLibs = process.env.MILO_LIBS || '';`
   ` await page.goto(`${baseURL}${features[0].path}${miloLibs}`);`

Also, can you pls copy the corresponding test pages into the CC Nala SharePoint folder?

**Review by skumar09 — APPROVED** [review]

**Comment by afmicka** [comment]
> @afmicka : sure, thanks for the update; PR looks good; I will merge it. Can you please make the following changes as part of another PR?
> 
> I have recently updated all the Milo tests to be run using the Milolibs param ([PR-240](https://github.com/adobecom/nala/pull/240)), so can you please do the following updates as part of the next PR? ( Please refer to any of the Milo tests.) `const miloLibs = process.env.MILO_LIBS || '';` ` await page.goto(`${baseURL}${features[0].path}${miloLibs}`);`
> 
> Also, can you pls copy the corresponding test pages into the CC Nala SharePoint folder?

Sure, will do. Thanks.

**Pull request merged**
